function ranking = loadSpatialWaveFinalRanking(searchFilename)
%LOADSPATIALWAVEFINALRANKING Read the accepted-fit ranking, never old ABC scores.
% SEARCHFILENAME is the existing ABC-original-...mat name. The adjacent
% FinalFit-original-...mat manifest is published by the revised runner.
[folder,name,ext]=fileparts(searchFilename);
if ~strncmp(name,'ABC-original-',13)
    error('SpatialWave:InvalidRankingFilename','Expected an ABC-original-...mat filename.');
end
filename=fullfile(folder,['FinalFit-' name(5:end) ext]);
if exist(filename,'file')~=2
    error('SpatialWave:FinalFitResultsRequired', ...
        ['No accepted-fit ranking exists for these settings. Rerun ' ...
         'Run_SW_subepidemicFramework, then regenerate plots and forecasts. ' ...
         'Legacy search AICc will not be substituted.']);
end
ranking=load(filename);
required={'schemaVersion','fitRunId','rankingScope','RMSES','PS','relativelik_i','fits','numModels','DT'};
if ~all(isfield(ranking,required)) || ranking.schemaVersion~=1 || ...
        ~strcmp(ranking.rankingScope,'selected-refitted-models') || ...
        ranking.numModels~=size(ranking.RMSES,1) || ...
        ranking.numModels~=numel(ranking.fits) || ...
        size(ranking.PS,1)~=ranking.numModels || ...
        numel(ranking.relativelik_i)~=ranking.numModels || ...
        any(~isfinite(ranking.RMSES(:,4)))
    error('SpatialWave:InvalidFinalFitRanking','Invalid or incomplete accepted-fit manifest.');
end
end
