function fit = makeSpatialWaveAcceptedFit(P,Pstart,bestfit,components,data1,target, ...
    method1,dist1,npatches,flag1,onset_thr,typedecline1,onset_fixed, ...
    optimizerObjective,exitflag,output,searchRank,searchAICc,searchRelativeLikelihood)
%MAKESPATIALWAVEACCEPTEDFIT Freeze and score the accepted (pre-bootstrap) fit.
% No integration or optimization is performed here. The scored curve is the
% actual final curve, not an optimizer's last global yfit or its initializer.
% Existing likelihood constants, zero handling and parameter-count rules are
% retained. This does not repair onset dynamics or NB data conventions.

P=P(:)'; Pstart=Pstart(:)'; bestfit=bestfit(:); target=target(:);
if numel(P)~=7 || ~isreal(P) || any(~isfinite(P)) || ...
        numel(Pstart)~=7 || ~isreal(Pstart) || any(~isfinite(Pstart))
    error('SpatialWave:InvalidAcceptedParameters', ...
        'Accepted and initial parameter vectors must have seven finite real values.');
end
if ~isreal(bestfit) || any(~isfinite(bestfit)) || isempty(bestfit) || ...
        ~isreal(target) || any(~isfinite(target)) || numel(bestfit)~=numel(target) || ...
        size(data1,1)~=numel(target) || size(data1,2)~=2 || ...
        size(components,1)~=numel(target) || size(components,2)~=npatches || ...
        ~isreal(components) || any(~isfinite(components(:)))
    error('SpatialWave:InvalidAcceptedCurve', ...
        'Accepted curve, component trajectories and calibration target must agree in length and be finite and real.');
end
n=numel(target);
k=get_nparams(method1,dist1,npatches,flag1,1,onset_fixed);
if n<=k+1
    error('SpatialWave:UnsupportedFinalFitAICc', ...
        'Cannot report final-fit AICc with n=%d and k=%d; n must exceed k+1.',n,k);
end
if sum(bestfit)==0
    error('SpatialWave:InvalidAcceptedCurve', ...
        'The all-zero-curve optimization penalty is not a final-fit likelihood.');
end
[fval,scoringCurve]=getSpatialWaveObjective(target,bestfit,method1,P(end-1),P(end));
if ~isscalar(fval) || ~isreal(fval) || ~isfinite(fval)
    error('SpatialWave:InvalidAcceptedObjective', ...
        'The objective evaluated on the accepted curve must be finite and real.');
end
[AICc,part1,part2,kAICc]=getAICc(method1,dist1,npatches,flag1,1,fval,n,onset_fixed);
if k~=kAICc || ~isscalar(AICc) || ~isreal(AICc) || ~isfinite(AICc)
    error('SpatialWave:InvalidAcceptedAICc', ...
        'The accepted curve must produce a finite real AICc with a consistent parameter count.');
end
fit=struct('schemaVersion',1,'parameters',P,'initialParameters',Pstart, ...
    'modelSpec',[npatches onset_thr typedecline1], ...
    'method',method1,'distribution',dist1,'growthModel',flag1, ...
    'onsetFixed',onset_fixed,'data',data1,'target',target, ...
    'bestfit',bestfit,'componentCurves',components,'scoringCurve',scoringCurve, ...
    'objectiveValue',fval,'optimizerObjectiveValue',optimizerObjective, ...
    'optimizerExitflag',exitflag,'optimizerOutput',output, ...
    'numObservations',n,'numParameters',k,'AICc',AICc, ...
    'AICcFitTerm',part1,'AICcPenaltyTerm',part2, ...
    'searchRank',searchRank,'searchAICc',searchAICc, ...
    'searchRelativeLikelihood',searchRelativeLikelihood, ...
    'rank',NaN,'relativeLikelihood',NaN);
end
